---
version: "3.8"
services:
  cricket:
    image: sravanthi777/zepto:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
  zomato:
    image: sravanthi777/blinkit:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
  swiggy:
    image: sravanthi777/ola:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
  hotstar:
    image: sravanthi777/rapido:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
